<?php


namespace Zf3Bootstrap4Forms\Form\Element;


use Zend\Form\Element;
use Zend\Form\ElementInterface;

class Between extends Element\Number implements RangeInterface
{
    public function setAttributes($arrayOrTraversable)
    {
        parent::setAttributes($arrayOrTraversable); // TODO: Change the autogenerated stub
        if (!array_key_exists("id", $arrayOrTraversable))
            $this->setAttribute("id", $this->getName()."ID");
    }

    /**
     * Provide default input rules for this element
     *
     * Attaches default validators for the datetime input.
     *
     * @return array
     */
    public function getInputSpecification()
    {
        return [
            'name' => $this->getName(),
            'required' => false,
            'allow_empty' => false,
            'validators' => array_merge($this->getValidators(), array(
                array('name' => 'Digits')
            ))
        ];
    }
}