<?php


namespace Zf3Bootstrap4Forms\Form\Element;


use Zend\Form\Element;
use Zend\InputFilter\InputProviderInterface;
use Zend\ModuleManager\Feature\ViewHelperProviderInterface;
use Zend\Validator\Date;

class DateRange extends Element\DateTime implements RangeInterface
{

    public function setAttributes($arrayOrTraversable)
    {
        parent::setAttributes($arrayOrTraversable); // TODO: Change the autogenerated stub
        if (!array_key_exists("id", $arrayOrTraversable))
            $this->setAttribute("id", $this->getName()."ID");
    }

    /**
     * Provide default input rules for this element
     *
     * Attaches default validators for the datetime input.
     *
     * @return array
     */
    public function getInputSpecification()
    {
        return [
            'name' => $this->getName(),
            'required' => false,
            'allow_empty' => false,
            'filters'    => array(
                array('name' => 'StripTags'),
                array('name' => 'StringTrim'),
                array(
                    'name' => 'Callback',
                    'options' => array(
                        'callback' => function($value) {

                            if (is_string($value) && !empty($value)) {
                                $value = \DateTime::createFromFormat($this->getFormat(), $value);
                            } else {
                                return null;
                            }

                            return $value;

                        },
                    ),
                ),
            ),
            'validators' => $this->getValidators(),
        ];
    }
}