<?php

namespace Zf3Bootstrap4Forms\View\Helper;

use Zend\Form\ElementInterface;

class FormInput extends \Zend\Form\View\Helper\FormInput
{
    public function render(ElementInterface $element)
    {
        if ($element->getMessages()) {
            if (!preg_match('/(^| )is-invalid($| )/', $element->getAttribute('class'))) {
                $element->setAttribute('class', trim($element->getAttribute('class') . ' is-invalid'));
            }
        }

        return parent::render($element); // TODO: Change the autogenerated stub
    }

}