<?php

namespace Zf3Bootstrap4Forms\View\Helper;

use Zend\Form\ElementInterface;

class FormLabel extends \Zend\Form\View\Helper\FormLabel
{
    public function __invoke(ElementInterface $element = null, $labelContent = null, $position = null)
    {
        if ($element->getOption('formType') === Form::TYPE_HORIZONTAL) {
            $labelAttributes = $element->getAttributes();

            if (!array_key_exists('class', $labelAttributes) || !preg_match('/(^| )col-form-label($| )/', $labelAttributes['class'])) {
                $class = array_key_exists('class', $labelAttributes) ? $labelAttributes['class'] : '';
                $class .= ' col-form-label';
                $labelAttributes['class'] = trim($class);
                $element->setLabelAttributes($labelAttributes);
            }
        }

        return parent::__invoke($element, $labelContent, $position); // TODO: Change the autogenerated stub
    }

}