<?php

namespace Zf3Bootstrap4Forms\View\Helper;

use Zend\Form\ElementInterface;

class FormCollection extends \Zend\Form\View\Helper\FormCollection
{
    public function __invoke(ElementInterface $element = null, $wrap = true)
    {
        // render elemnts and fieldsets accordingly
        if ($element->getOption('formType', Form::TYPE_HORIZONTAL)) {
            // elements
            foreach ($element->getElements() as $fieldsetElement) {
                $fieldsetElement->setOption('formType', Form::TYPE_HORIZONTAL);
            }

            // fieldsets
            foreach ($element->getFieldsets() as $fieldsetFieldset) {
                $fieldsetFieldset->setOption('formType', Form::TYPE_HORIZONTAL);
            }
        }

        return parent::__invoke($element, $wrap); // TODO: Change the autogenerated stub
    }

}