<?php

namespace Zf3Bootstrap4Forms\View\Helper;

use Zend\Form\Element;
use Zend\Form\FormInterface;

class Form extends \Zend\Form\View\Helper\Form
{
    const TYPE_HORIZONTAL = 'horizontal';

    public function __invoke(FormInterface $form = null, $type = null)
    {
        if ($type === static::TYPE_HORIZONTAL) {
            /** @var Element $element */
            foreach ($form->getElements() as $element) {
                $element->setOption('formType', static::TYPE_HORIZONTAL);
            }
        }

        return parent::__invoke($form); // TODO: Change the autogenerated stub
    }

}