<?php

namespace Zf3Bootstrap4Forms\View\Helper;

use Zend\Form\ElementInterface;

class FormRowHorizontal extends FormRow
{
    public function render(ElementInterface $element, $labelPosition = null)
    {
        $element->setOption('formType', Form::TYPE_HORIZONTAL);

        $labelAttributes = $element->getLabelAttributes();

        if (!is_array($labelAttributes) || !array_key_exists('class', $labelAttributes) || !preg_match('/(^| )col-form-label($| )/', $labelAttributes['class'])) {
            $class = array_key_exists('class', $labelAttributes) ? $labelAttributes['class'] : '';
            $class .= ' col-form-label';
            $labelAttributes['class'] = trim($class);
            $element->setLabelAttributes($labelAttributes);
        }

        return parent::render($element, $labelPosition); // TODO: Change the autogenerated stub
    }


}