<?php

namespace Zf3Bootstrap4Forms\View\Helper;

use Zend\Form\Element\Csrf;
use Zend\Form\Element\Hidden;
use Zend\Form\ElementInterface;

class FormElementErrors extends \Zend\Form\View\Helper\FormElementErrors
{
    protected $messageOpenFormat = '<div%s>';
    protected $messageSeparatorString = '.<br>';
    protected $messageCloseString = '</div>';

    protected $attributes = [
        'class' => 'invalid-feedback'
    ];

    public function render(ElementInterface $element, array $attributes = [])
    {
        // add margin to invalid message for hidden / csrf elements
        if ($element instanceof Hidden || $element instanceof Csrf) {
            $this->attributes['class'] .= ' mb-3';
        }

        return parent::render($element, $attributes); // TODO: Change the autogenerated stub
    }


}