<?php

namespace Zf3Bootstrap4Forms\View\Helper;

use Zend\Form\Element\Checkbox;
use Zend\Form\Element\Radio;
use Zend\Form\ElementInterface;

class FormRowHorizontal extends FormRow
{
    public function render(ElementInterface $element, $labelPosition = null)
    {
        $element->setOption('formLayout', Form::LAYOUT_HORIZONTAL);

        $labelAttributes = $element->getLabelAttributes();

        if (!$element instanceof Checkbox && !$element instanceof Radio) {
            if (!is_array($labelAttributes) || !array_key_exists('class', $labelAttributes) || !preg_match('/(^| )col-form-label($| )/', $labelAttributes['class'])) {
                $class = array_key_exists('class', $labelAttributes) ? $labelAttributes['class'] : '';
                $class .= ' col-form-label';
                $labelAttributes['class'] = trim($class);
                $element->setLabelAttributes($labelAttributes);
            }
        }

        return parent::render($element, $labelPosition); // TODO: Change the autogenerated stub
    }


}