<?php

namespace Zf3Bootstrap4Forms\View\Helper;


use Zend\Form\Element\Checkbox;
use Zend\Form\ElementInterface;

class FormRow extends \Zend\Form\View\Helper\FormRow
{
    public function render(ElementInterface $element, $labelPosition = null)
    {
        if ($element instanceof Checkbox) {
            // default label to append
            $element->setLabelOption('label_position', $element->getLabelOption('label_position') ?: \Zend\Form\View\Helper\FormRow::LABEL_APPEND);
        }

        return parent::render($element, $labelPosition); // TODO: Change the autogenerated stub
    }

}