<?php

namespace Zf3Bootstrap4Forms\View\Helper;

use Zend\Form\Element;
use Zend\Form\FormInterface;

class Form extends \Zend\Form\View\Helper\Form
{
    const LAYOUT_HORIZONTAL = 'horizontal';
    const LAYOUT_FLOATING_LABLES = 'floating-labels';

    protected $layouts = [
        self::LAYOUT_FLOATING_LABLES,
        self::LAYOUT_HORIZONTAL
    ];

    public function __invoke(FormInterface $form = null, $type = null)
    {
        // render elemnts and fieldsets accordingly
        if (in_array($type, $this->layouts)) {
            // elements
            /** @var Element $element */
            foreach ($form->getElements() as $element) {
                $element->setOption('formLayout', $type);
            }

            // fieldsets
            foreach ($form->getFieldsets() as $fieldset) {
                $fieldset->setOption('formLayout', $type);
            }
        }

        return parent::__invoke($form); // TODO: Change the autogenerated stub
    }

}