<?php

/**
 * TODO:
 * - Make options for js configurable
 * - Include js library in module
 */

/**
 * @var \Zend\Form\Element $element
 */
if (is_null($this->fromElement) || is_null($this->toElement))
    throw new \Exception("Either one or both needed elements missing: Please add option key 'fromElement' and 'toElement' to according dateRange elements.");

// Extract locale
$locale = $this->plugin('translate')->getTranslator()->getLocale();
$jsLocale = strtolower(explode("_", $locale)[0]);

?>

<div class="input-daterange input-group" data-date-today-btn="linked" data-date-language="de"
     data-date-format="dd.mm.yyyy" data-date-today-highlight="true">
    <?php echo $this->formInput($this->fromElement); ?>
    <div class="input-group-prepend input-group-append">
        <div class="input-group-text">
            <i class="fa fa-fw fa-arrows-h"></i>
        </div>
    </div>
    <?php echo $this->formInput($this->toElement); ?>
</div>
<?php
/*
@TODO: HOW CAN WE MANAGE ASSETS PROPERLY?

$this->headLink()->appendStylesheet('/vendor/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css'); ?>
<?php $this->inlineScript()->appendFile('/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js', 'text/javascript'); ?>
<?php if (is_readable(getcwd() . '/public/vendor/bootstrap-datepicker/dist/locales/bootstrap-datepicker.' . $jsLocale . '.min.js'))
    $this->inlineScript()->appendFile('/vendor/bootstrap-datepicker/dist/locales/bootstrap-datepicker.' . $jsLocale . '.min.js', 'text/javascript'); ?>
<?php $this->inlineScript()->captureStart();
echo <<<JS
    $(function () {
        $('.input-daterange').datepicker();
    });
JS;
$this->inlineScript()->captureEnd(); */
?>